backend:
  name: git-gateway
  branch: astro

publish_mode: editorial_workflow

media_folder: 'public'
public_folder: '/'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image' }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
